server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backManagedb?serverTimezone=GMT%2B8
    username: root
    password: 123456
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

#扫描所有mapper文件
mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


